name: Build

on: [ workflow_dispatch, push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build with Gradle
        run: chmod u+x ./gradlew && ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          path: build/libs/*.jar

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-path: build/libs/*.jar
